common/urls.py
from django.urls import path
from common import views

app_name = 'common'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

dineDesk/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('menu/', include('menu.urls')),
    path('orders/', include('orders.urls')),
    path('tables/', include('tables.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from django.urls import path, include
from menu import views

app_name = 'menu'

categories_paths = [
    path('', views.CategoryListView.as_view(), name='category-list'),
    path('add/', views.CategoryCreateView.as_view(), name='category-create'),
    path('<int:pk>/add-menuitem/', views.MenuItemCreateView.as_view(), name='menuitem-create'),
    path('detail/<int:pk>', views.CategoryDetailView.as_view(), name='category-detail'),
    path('edit/<int:pk>', views.CategoryEditView.as_view(), name='category-edit'),
    path('delete/<int:pk>', views.CategoryDeleteView.as_view(), name='category-delete'),
]

item_paths = [
    path('', views.MenuItemDetailView.as_view(), name='menuitem-detail'),
    path('edit/', views.MenuItemEditView.as_view(), name='menuitem-edit'),
    path('delete/', views.MenuItemDeleteView.as_view(), name='menuitem-delete'),
]

urlpatterns = [
    path('categories/', include(categories_paths)),
    path('item/<int:pk>/', include(item_paths)),
]

tables/urls.py
from django.urls import path
from tables import views


app_name = 'tables'

urlpatterns = [
    path('', views.TableListView.as_view(), name='list'),
    path('create/', views.TableCreateView.as_view(), name='create'),
    path('<int:pk>/', views.TableDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', views.TableEditView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.TableDeleteView.as_view(), name='delete'),
]

common/models.py
from django.db import models

# Create your models here.

common/views.py
from django.views.generic import TemplateView

from menu.models import MenuItem
from orders.models import Order
from tables.models import Table


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["menu_items_count"] = MenuItem.objects.count()
        context["active_orders"] = Order.objects.filter(status="pending").count()
        context["tables_count"] = Table.objects.count()

        return context

templates/common/footer.html
<footer class="footer mt-auto py-3 bg-info text-dark">
    <div class="container text-center">
        <span>&copy; 2024 DineDesk. All rights reserved.</span>
    </div>
</footer>

templates/common/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-info">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'common:home' %}">DineDesk</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'common:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'menu:category-list' %}">Menu</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tables:list' %}">Tables</a>
                </li>
            </ul>
        </div>
    </div>
</nav>